function DragIcon({ className }: { className: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      {/* <rect width="24" height="24" fill="white" /> */}
      <circle
        cx="9.5"
        cy="6"
        r="0.5"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="9.5"
        cy="10"
        r="0.5"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="9.5"
        cy="14"
        r="0.5"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="9.5"
        cy="18"
        r="0.5"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="14.5"
        cy="6"
        r="0.5"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="14.5"
        cy="10"
        r="0.5"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="14.5"
        cy="14"
        r="0.5"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle
        cx="14.5"
        cy="18"
        r="0.5"
        stroke="#000000"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

export default DragIcon;
